/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file    freertos.c
  * @brief   FreeRTOS task implementations for STM32H743 UART logging demo
  *
  * Tasks:
  *   SensorTask  (P3) — simulates ADC sensor polling, pushes to logQueue
  *   LedTask     (P2) — heartbeat LED toggle via BSP
  *   LoggerTask  (P1) — drains logQueue, transmits over USART3 (BSP COM1)
  *   WriterTask  (P4) — mutex-protected shared buffer writes
  *
  * IPC:
  *   logQueue    — 10 items x 64 bytes, all tasks → LoggerTask
  *   sharedMutex — protects shared_buf between WriterTask and readers
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "FreeRTOS.h"
#include "task.h"
#include "main.h"
#include "cmsis_os.h"

/* Private includes ----------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "stdio.h"
#include "string.h"
#include "stm32h7xx_nucleo.h"   /* BSP header — hcom_uart[], BSP_LED_Toggle() */
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */

/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN Variables */

/* BSP COM1 handle — USART3 on PD8/PD9, pre-initialised in main.c */
extern UART_HandleTypeDef hcom_uart[COMn];

/* Shared buffer protected by sharedMutex */
static char shared_buf[32] = {0};

/* USER CODE END Variables */

/* Declarations for RTOS objects — generated by CubeMX, defined in main.c */
extern osMessageQueueId_t logQueueHandle;
extern osMutexId_t        sharedMutexHandle;

/* Private function prototypes -----------------------------------------------*/
/* USER CODE BEGIN FunctionPrototypes */

/* USER CODE END FunctionPrototypes */

void MX_FREERTOS_Init(void); /* Called from main.c */

/**
  * @brief  FreeRTOS initialization — called once before osKernelStart()
  *         Tasks, queue, and mutex are created by CubeMX-generated code.
  *         Do NOT add task creation here manually.
  */
void MX_FREERTOS_Init(void)
{
  /* USER CODE BEGIN Init */

  /* USER CODE END Init */
  /* CubeMX generates task/queue/mutex creation code here automatically */
}

/* USER CODE BEGIN Header_SensorTask */
/**
  * @brief  Sensor polling task
  *         Simulates reading an ADC value every 500 ms and pushes a
  *         formatted log message to logQueue. Replace the simulated
  *         adc_val with a real HAL_ADC_GetValue() call when hardware
  *         is available.
  * @param  argument: unused
  * @retval None
  */
/* USER CODE END Header_SensorTask */
void SensorTask(void *argument)
{
  /* USER CODE BEGIN SensorTask */
  char     msg[64];
  uint32_t tick    = 0;
  uint32_t adc_val = 0;

  for (;;)
  {
    /* Simulate ADC reading — replace with real ADC when hardware ready */
    adc_val = HAL_GetTick() % 4096;

    snprintf(msg, sizeof(msg),
             "[SENSOR] tick=%lu  adc=%lu\r\n", tick++, adc_val);

    /* Non-blocking push — if queue is full, message is dropped silently */
    osMessageQueuePut(logQueueHandle, msg, 0, 0);

    osDelay(500);   /* yield CPU for 500 ms */
  }
  /* USER CODE END SensorTask */
}

/* USER CODE BEGIN Header_LedTask */
/**
  * @brief  LED heartbeat task
  *         Toggles the green Nucleo LED every 250 ms to prove the
  *         scheduler is alive. Also sends a log message so the toggle
  *         is visible in the UART terminal.
  * @param  argument: unused
  * @retval None
  */
/* USER CODE END Header_LedTask */
void LedTask(void *argument)
{
  /* USER CODE BEGIN LedTask */
  char     msg[32];
  uint32_t count = 0;

  for (;;)
  {
    BSP_LED_Toggle(LED_GREEN);

    snprintf(msg, sizeof(msg), "[LED]    toggle #%lu\r\n", count++);
    osMessageQueuePut(logQueueHandle, msg, 0, 0);

    osDelay(250);
  }
  /* USER CODE END LedTask */
}

/* USER CODE BEGIN Header_LoggerTask */
/**
  * @brief  UART logger task
  *         Blocks on logQueue — zero CPU usage while queue is empty.
  *         When a message arrives, transmits it over USART3 (ST-Link
  *         VCP) using the BSP COM1 handle.
  *         This is the only task that touches the UART — no mutex
  *         needed on the peripheral itself.
  * @param  argument: unused
  * @retval None
  */
/* USER CODE END Header_LoggerTask */
void LoggerTask(void *argument)
{
  /* USER CODE BEGIN LoggerTask */
  char msg[64];

  for (;;)
  {
    /* Block indefinitely until a message is available — no CPU waste */
    if (osMessageQueueGet(logQueueHandle, msg, NULL, osWaitForever) == osOK)
    {
      /* Blocking transmit — simple and safe for a single logger task */
      HAL_UART_Transmit(&hcom_uart[COM1],
                        (uint8_t *)msg,
                        (uint16_t)strlen(msg),
                        100);
    }
  }
  /* USER CODE END LoggerTask */
}

/* USER CODE BEGIN Header_WriterTask */
/**
  * @brief  Mutex-protected shared buffer writer task
  *         Demonstrates proper mutex usage: acquire with timeout,
  *         write to shared resource, release immediately.
  *         The 100 ms timeout prevents deadlock — if the mutex is
  *         never released by another holder, WriterTask skips the
  *         write and retries after 700 ms.
  * @param  argument: unused
  * @retval None
  */
/* USER CODE END Header_WriterTask */
void WriterTask(void *argument)
{
  /* USER CODE BEGIN WriterTask */
  char     log[64];
  uint32_t count = 0;

  for (;;)
  {
    /* Acquire mutex — block up to 100 ms before giving up */
    if (osMutexAcquire(sharedMutexHandle, 100) == osOK)
    {
      /* Critical section — shared_buf is protected here */
      snprintf(shared_buf, sizeof(shared_buf), "count=%lu", count++);

      osMutexRelease(sharedMutexHandle);  /* release as fast as possible */

      /* Log outside the critical section — never hold mutex during I/O */
      snprintf(log, sizeof(log),
               "[WRITER] shared_buf: %s\r\n", shared_buf);
      osMessageQueuePut(logQueueHandle, log, 0, 0);
    }

    osDelay(700);
  }
  /* USER CODE END WriterTask */
}

/* USER CODE BEGIN Application */

/**
  * @brief  Stack overflow hook
  *         Called by FreeRTOS if a task writes past the end of its stack.
  *         configCHECK_FOR_STACK_OVERFLOW must be 1 or 2 in FreeRTOSConfig.h
  *         Halts with IRQs disabled — attach debugger and inspect pcTaskName
  *         to identify which task overflowed.
  */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
  (void)xTask;
  (void)pcTaskName;
  __disable_irq();
  for (;;);
}

/**
  * @brief  Malloc failed hook
  *         Called by FreeRTOS if pvPortMalloc() returns NULL.
  *         Increase configTOTAL_HEAP_SIZE in FreeRTOSConfig.h if this triggers.
  */
void vApplicationMallocFailedHook(void)
{
  __disable_irq();
  for (;;);
}

/* USER CODE END Application */
